### ISSUE TITLE
Marathon

### ISSUE THREAD

**Issue by cosmonot1** [JoshuaKGoldberg/joshuakgoldberg-dot-com-old#15]
Trash game. Trash series. Trash. Should be updated to say Mass Effect Andromeda is the best game ever made.

**Comment by JoshuaKGoldberg** [comment]
![no](https://i.imgur.com/BATNJOV.png)

**Comment by cosmonot1** [comment]
</3

**Comment by JoshuaKGoldberg** [comment]
<3
