### ISSUE TITLE
Invalid Linkedin url

### ISSUE THREAD

**Issue by asponda** [JoshuaKGoldberg/joshuakgoldberg-dot-com-old#43]
### Subject of the issue
Hi! Your linkedin link is navigating to https://linked.com/in/joshuakgoldberg, that it's an invalid page.

### Steps to reproduce

1. Go to http://www.joshuakgoldberg.com/#contact
2. Click Linkedin link

### Expected behaviour
Open the linkedin profile page

### Actual behaviour
Opening an invalid page.

**Comment by JoshuaKGoldberg** [comment]
LOL

**Comment by JoshuaKGoldberg** [comment]
Thanks @asponda 😄 !
